name: mobileapp
description: "Version 1 de l'application mobile du projet morpheus"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.0.0
  camera: ^0.10.5+9
  tflite_flutter: ^0.10.4
  video_player: ^2.8.6
  google_mlkit_pose_detection: ^0.12.0
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true

  # ressources de l'application
  assets:
    - assets/api/
    - assets/images/
    - assets/detection/

  fonts:
    - family: "Poppins"
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-SemiBold.ttf
    - family: "OpenSans"
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-Medium.ttf
